sudo: required
dist: trusty

language:
    - c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - doxygen
    - valgrind
    - clang
    - gcc
    - gcc-6
    - python3-pip
before_install:
   - sudo -H python3 -m pip install pip==8.1.1
install: test/travis-install.sh
script: test/travis-build.sh

